### ISSUE TITLE
Figured I'd help since I was just in the same boat

### ISSUE THREAD

**Issue by jcorum11** [margaretelson/Weather-API-Site#1]
https://github.com/jcorum11/Storm.ly
https://github.com/TRemigi/weather-dashboard
https://github.com/JohnNielsen1221/weather-dashboard
https://github.com/parkerrobison/weather-dashboard
https://github.com/kaileymorter/weather-city-dashboard

All of us averaged >==95% in the course and stole each other's code frequently. It seems we have the same curriculum so I would use our repos as a resource for the rest of your projects. Share with whoever you like :)

**Comment by margaretelson** [comment]
Thank you so much!!

**Comment by margaretelson** [comment]
Any help is much appreciated!

**Comment by jcorum11** [comment]
NP!
